# Generated by Django 3.1.5 on 2021-01-08 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210108_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
