# Generated by Django 3.1.5 on 2021-01-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210111_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='refferal_code',
            field=models.CharField(blank=True, default='c1028', max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='wallet',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
    ]
