# Generated by Django 3.1.5 on 2021-01-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210111_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='refferal_code',
            field=models.CharField(blank=True, default='689ba', max_length=150),
        ),
    ]
