# Generated by Django 3.1.5 on 2021-01-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210115_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='refferal_code',
            field=models.CharField(blank=True, default='53f3f', max_length=150),
        ),
    ]
