# Generated by Django 3.1.5 on 2021-01-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210115_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='refferal_code',
            field=models.CharField(blank=True, default='eda60', max_length=150),
        ),
    ]
