# Generated by Django 3.1.5 on 2021-01-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210118_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpaypayment',
            name='status',
            field=models.CharField(default='nas', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='refferal_code',
            field=models.CharField(blank=True, default='cb6bf', max_length=150),
        ),
    ]
